version: "3.1"
services:
  db:
    container_name: bipi-postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
    external: false
